"""Перевірка коду зі схеми: усі фрагменти C# збираються в мініпроєкт і виконуються."""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path

CSPROJ = """<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <RootNamespace>DiagramCheck</RootNamespace>
    <NoWarn>CS0168;CS0219;CS8321</NoWarn>
  </PropertyGroup>
</Project>
"""


def write_project(spec: dict, snippets: list[str], out_dir: Path) -> Path | None:
    chk = spec.get("check")
    if not chk:
        return None
    out_dir.mkdir(parents=True, exist_ok=True)
    src = ["// <auto-generated> з tools/diagrams/specs/" + spec["id"] + ".yaml — не редагувати вручну",
           *[f"using {u};" for u in chk.get("usings", ["System"])], "",
           "// ── контекст (у схемі не показано)", *str(chk.get("context", "")).splitlines(), "",
           "// ── код зі схеми", *snippets, "",
           "// ── твердження", *str(chk.get("asserts", "")).splitlines(),
           'Console.WriteLine("CHECK OK");', "",
           "// ── типи", *str(chk.get("types", "")).splitlines(), ""]
    (out_dir / "Program.cs").write_text("\n".join(src), encoding="utf-8")
    (out_dir / "DiagramCheck.csproj").write_text(CSPROJ, encoding="utf-8")
    return out_dir


def run_project(proj: Path) -> tuple[bool, str]:
    if not shutil.which("dotnet"):
        return False, "dotnet не знайдено — перевірку коду пропущено"
    r = subprocess.run(["dotnet", "run", "--project", str(proj), "-v", "q", "-nologo"],
                       capture_output=True, text=True, encoding="utf-8", timeout=300)
    out = (r.stdout + r.stderr).strip()
    return r.returncode == 0 and "CHECK OK" in r.stdout, out
